"""Renamed road_location and detection_status columns

Revision ID: a643670e6e30
Revises: bd168c581f1e
Create Date: 2025-11-13 10:36:39.226921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a643670e6e30'
down_revision = 'bd168c581f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=True))
        batch_op.drop_column('detection_status')
        batch_op.drop_column('road_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('road_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('detection_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
